/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e3bdc7",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "outline": "#aa8892",
        "outline-variant": "#5b3f48",
        "surface-tint": "#ffb0ca",
        "primary": "#ffb0ca",
        "on-primary": "#640036",
        "primary-container": "#ff479c",
        "on-primary-container": "#58002f",
        "inverse-primary": "#b90068",
        "secondary": "#fff9ef",
        "on-secondary": "#3a3000",
        "secondary-container": "#ffdb3c",
        "on-secondary-container": "#725f00",
        "tertiary": "#ffb0d0",
        "on-tertiary": "#63003d",
        "tertiary-container": "#ed5ba5",
        "on-tertiary-container": "#570035",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#ffb0ca",
        "on-primary-fixed": "#3e001f",
        "on-primary-fixed-variant": "#8d004e",
        "secondary-fixed": "#ffe16d",
        "secondary-fixed-dim": "#e9c400",
        "on-secondary-fixed": "#221b00",
        "on-secondary-fixed-variant": "#544600",
        "tertiary-fixed": "#ffd8e6",
        "tertiary-fixed-dim": "#ffb0d0",
        "on-tertiary-fixed": "#3d0024",
        "on-tertiary-fixed-variant": "#8c0058",
        "background": "#000000",
        "on-background": "#e2e2e2",
        "surface-variant": "#353535",
        // Accents from code
        "primary-pink": "#FF69B4",
        "deep-pink": "#FF1493",
        "royal-gold": "#FFD700",
      },
      fontFamily: {
        "display-royal": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "container-margin": "20px",
        "gutter": "16px",
      }
    },
  },
  plugins: [],
}
